### ISSUE TITLE
Customise Options

### ISSUE THREAD

**Issue by codeXco** [toddmotto/html5blank#102]
Loving the theme, very well thought out and saves a lot of time.

However, it would be nice to have more customize options, in particular, the options to set the header text / tagline, on / off and maybe set your logo through a custom function rather than hard coding it.

An example on how you might do this can be found here:

http://kwight.ca/2012/12/02/adding-a-logo-uploader-to-your-wordpress-site-with-the-theme-customizer/

Thanks again and keep up the good work!

Regards,
Codex

**Comment by oriSomething** [comment]
Hey,
first of all, if you would like to make PRs, it will be more than welcome (and better that the PRs will be on separates topics, so it will be easier to merge if there is a problem in one of them).

- first, tagline you can specify from the wordpress settings. so it's existed already.
- second, this theme made for programmers and ment to be minimalist so it will make it easy to take it to your direction, and with WP you can do so many things, so i don't think this project should be the opinionated about what WP site should be and look.
- third, about the logo, because it meant to programmers, i don't think this option make it an easy feature. anyway when you create a custom theme to someone, the logo doesn't supposed to be change during the life of the theme. so making this logic most likely will make this project more complex.
if you have programmatically good ideas how to solve it, and make it harder to use. you more than welcome.
