### ISSUE TITLE
add_theme_support for infinite-scroll

### ISSUE THREAD

**Issue by EricWVGG** [toddmotto/html5blank#113]
This would entail making content.php and content-page.php templates, then modifying page.php to pull them using get_template_part( 'content', 'search' ), a lá the twentyfifteen theme.

If I put together a branch like that, is that something you might someday be interested in pulling into the theme?

(or is this something proprietary to Jetpack? I'm a little unclear)

**Comment by oriSomething** [comment]
i need to make a little research about it, but if it doesn't make the code complex i don't see any problem with merging it.
how much code do you think involved here?
how different will it make making themes from what we have today?
because i don't like the idea of adding `JavaScript` to enable this by default, what do you expect of the complexity / size of the JS file to enable it be?

about the JS part, because it's a scaffold i can't sure how anyone will be build the client side, if a few years ago it was clear that `jQuery` is the way to go, today we have `jQuery`, `Ember`, `React`, `Angular`, `Vanilla JS` and more wide use options… so i'm not favor of giving the JS part inside.

**Comment by EricWVGG** [comment]
Very much agree that javascript should not be rolled into the theme. 

Upon further investigation, it appears that I mistook add_theme_support('infinite-scroll') as a core Wordpress extension; this is actually provided by the Wordpress Jetpack plugin. All the javascript this would need is there.

But that said, I think it would be worth considering. Jetpack is by Wordpress, so if not core, it's pretty close. It would not disrupt usage of HTML5Blank w/o Jetpack — just rearrange a bit of the template structure. As a side benefit, it would make HTML5Blank more flexible for the use of custom-built infinite scroll and ajax loading; the changes would mirror stuff that I've manually built into HTML5Blank-based themes many times before. (and yes, serve-able by all sorts of techs, not just jQuery)

The big change is that you'd have files like content-post.php; single.php and archive.php would call to this include (once and in series respectively); the jetpack plugin would serve it up content-post.php serially. A custom-built infinite-loader would need to write their own code to collate the series, but this separation of "an article presentation" from "a list of articles" would still required, thus useful to have built into the theme.

**Comment by oriSomething** [comment]
i'm not afraid of adding more `php` files. the bottom line that it can make this project more flexible.
of course as long as it aligns with wordpress recommendations
