### ISSUE TITLE
Why are all the scripts loaded in <head>?

### ISSUE THREAD

**Issue by kremuwa** [toddmotto/html5blank#120]
I was surprised to see, that the conditionizr and modernizr scripts, as well as custom scripts.js file are all loaded in the `<head>` section of HTML document when using html5blank theme. Is there some specific reason to do this? As far as I know, it is considered good practice to load all the scripts just before the ending `</body>` tag, in order not to slow down the loading process of site's markup and CSS.

It could be achieved with the last parameter to wp_register_script function - it just has to be set to true. I will be happy to make a pull request unless there is some reason to keep it the way it is :)

**Comment by oriSomething** [comment]
first, `conditionizr` will probably removed and i'm not sure of the future of `modernizr` in this project (you can see here the problems with v3.0 https://www.youtube.com/watch?v=UPrlA8I9dm8 and also today when IE8 / Android 2.x are nearly not exist).

second, about the defer of loading scripts, it's a half lie that's being pushed in a lots of conferences video:
1. some scripts must run in the head. for example `conditionizr` and `modernizr`, because they related to the way the page render and even the ability to render some tags in old browsers. defering those scripts means broken site in some cases
2. about other scripts, it's more complicated, but `async` in most cases would still be better than putting scripts in `<body>`, and still depends on what you're doing

for now, i'll politely refuse, and you can add this in your site as needed.
