### ISSUE TITLE
Adding gulp-notify

### ISSUE THREAD

**Issue by mdaomega** [toddmotto/html5blank#123]
Using gulp-notify would be so helpful.

I'm learning laravel. it uses gulp-notify, I think It would be so helpful if html5blank also use it.

**Comment by oriSomething** [comment]
since there is a livereload i don't see a reason to bloat the dependencies more than it is now. and the other build process is fast enough.
the bottom line, my personal opinion is that i wouldn't want it and delete it in the minute after `git clone`. i really can't see how it's a "must" package, and i prefer to leave this repo as light weight as possible.
